// <auto-generated />
using System;
using DedicatedGeo.Mono.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DedicatedGeo.Mono.Dal.Migrations
{
    [DbContext(typeof(DatabaseRepository))]
    [Migration("20251211073058_AddUpdatedAtInDeviceStatuses")]
    partial class AddUpdatedAtInDeviceStatuses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("DedicatedGeo.Mono.Models.Device.DeviceStatus", b =>
                {
                    b.Property<Guid>("DeviceStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BatteryLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsButtonPressed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGPSOnline")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInAlarm")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInCharge")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceStatusId");

                    b.ToTable("DeviceStatuses");
                });

            modelBuilder.Entity("DedicatedGeo.Mono.Models.Location.LocationPoint", b =>
                {
                    b.Property<Guid>("LocationPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Point")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("LocationPointId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("LocationPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
