// <auto-generated />
using System;
using DedicatedGeo.Mono.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DedicatedGeo.Mono.Dal.Migrations
{
    [DbContext(typeof(DatabaseRepository))]
    [Migration("20251212191014_AddDeviceStatusHystories")]
    partial class AddDeviceStatusHystories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("DedicatedGeo.Mono.Models.Device.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("IMEI")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("QuarantineUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceId");

                    b.HasIndex("IMEI");

                    b.HasIndex("QuarantineUntil");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("DedicatedGeo.Mono.Models.Device.DeviceStatus", b =>
                {
                    b.Property<Guid>("DeviceStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BatteryLevel")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsButtonPressed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeviceOnline")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGPSOnline")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInAlarm")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInCharge")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceStatusId");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("DeviceStatuses");
                });

            modelBuilder.Entity("DedicatedGeo.Mono.Models.Device.DeviceStatusHistory", b =>
                {
                    b.Property<Guid>("DeviceStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceStatusHistoryId");

                    b.HasIndex("DeviceId", "StatusName", "ChangedAt");

                    b.ToTable("DeviceStatusHistories");
                });

            modelBuilder.Entity("DedicatedGeo.Mono.Models.Location.LocationPoint", b =>
                {
                    b.Property<Guid>("LocationPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Point")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("LocationPointId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeviceId", "CreatedAt");

                    b.ToTable("LocationPoints");
                });

            modelBuilder.Entity("DedicatedGeo.Mono.Models.Device.DeviceStatus", b =>
                {
                    b.HasOne("DedicatedGeo.Mono.Models.Device.Device", null)
                        .WithOne("DeviceStatus")
                        .HasForeignKey("DedicatedGeo.Mono.Models.Device.DeviceStatus", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DedicatedGeo.Mono.Models.Location.LocationPoint", b =>
                {
                    b.HasOne("DedicatedGeo.Mono.Models.Device.Device", null)
                        .WithMany("LocationPoints")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DedicatedGeo.Mono.Models.Device.Device", b =>
                {
                    b.Navigation("DeviceStatus")
                        .IsRequired();

                    b.Navigation("LocationPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
