// <auto-generated />
using System;
using DedicatedGeo.Mono.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DedicatedGeo.Mono.Dal.Migrations
{
    [DbContext(typeof(DatabaseRepository))]
    partial class DatabaseRepositoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("DedicatedGeo.Mono.Models.Device.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("IMEI")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceId");

                    b.HasIndex("IMEI");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("DedicatedGeo.Mono.Models.Device.DeviceAssignment", b =>
                {
                    b.Property<Guid>("DeviceAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceAssignmentId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId");

                    b.ToTable("DeviceAssignments");
                });

            modelBuilder.Entity("DedicatedGeo.Mono.Models.Device.DeviceStatus", b =>
                {
                    b.Property<Guid>("DeviceStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BatteryLevel")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsButtonPressed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeviceOnline")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGPSOnline")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInAlarm")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInCharge")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceStatusId");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("IsDeviceOnline", "UpdatedAt");

                    b.ToTable("DeviceStatuses");
                });

            modelBuilder.Entity("DedicatedGeo.Mono.Models.Device.DeviceStatusHistory", b =>
                {
                    b.Property<Guid>("DeviceStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceStatusHistoryId");

                    b.HasIndex("DeviceId", "StatusName", "ChangedAt");

                    b.ToTable("DeviceStatusHistories");
                });

            modelBuilder.Entity("DedicatedGeo.Mono.Models.Location.LocationPoint", b =>
                {
                    b.Property<Guid>("LocationPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Point")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("LocationPointId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeviceId", "CreatedAt");

                    b.ToTable("LocationPoints");
                });

            modelBuilder.Entity("DedicatedGeo.Mono.Models.User.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DedicatedGeo.Mono.Models.Device.DeviceAssignment", b =>
                {
                    b.HasOne("DedicatedGeo.Mono.Models.Device.Device", null)
                        .WithMany("DeviceAssignments")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DedicatedGeo.Mono.Models.Device.DeviceStatus", b =>
                {
                    b.HasOne("DedicatedGeo.Mono.Models.Device.Device", null)
                        .WithOne("DeviceStatus")
                        .HasForeignKey("DedicatedGeo.Mono.Models.Device.DeviceStatus", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DedicatedGeo.Mono.Models.Device.DeviceStatusHistory", b =>
                {
                    b.HasOne("DedicatedGeo.Mono.Models.Device.Device", null)
                        .WithMany("DeviceStatusHistories")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DedicatedGeo.Mono.Models.Location.LocationPoint", b =>
                {
                    b.HasOne("DedicatedGeo.Mono.Models.Device.Device", null)
                        .WithMany("LocationPoints")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DedicatedGeo.Mono.Models.Device.Device", b =>
                {
                    b.Navigation("DeviceAssignments");

                    b.Navigation("DeviceStatus")
                        .IsRequired();

                    b.Navigation("DeviceStatusHistories");

                    b.Navigation("LocationPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
